/**
 * Set-and-forget keep-alive for the home Mac while you travel.
 * Installs LaunchAgent + start script under Application Support (not Downloads — TCC-safe).
 */
import { execSync, spawn, type ChildProcess } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { appendActivity, loadConfig, saveConfig } from "./config.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

let caffeinateProc: ChildProcess | null = null;
let caffeinateWatch: ReturnType<typeof setInterval> | null = null;

export function supportDir(): string {
  return path.join(os.homedir(), "Library", "Application Support", "Porter");
}

export function logsDir(): string {
  return path.join(os.homedir(), "Library", "Logs");
}

function readBundleVersion(resources: string): string {
  if (process.env.PORTER_VERSION?.trim()) return process.env.PORTER_VERSION.trim();
  if (resources) {
    const v = path.join(resources, "VERSION");
    if (fs.existsSync(v)) {
      const t = fs.readFileSync(v, "utf8").trim();
      if (t) return t;
    }
  }
  try {
    const pkg = path.resolve(__dirname, "../../../package.json");
    if (fs.existsSync(pkg)) {
      const ver = (JSON.parse(fs.readFileSync(pkg, "utf8")) as { version?: string }).version;
      if (ver) return ver;
    }
  } catch {
    // ignore
  }
  return "0.0.0";
}

function resolvePorterRoot(): string {
  if (process.env.PORTER_RESOURCES) {
    return path.join(process.env.PORTER_RESOURCES, "app");
  }
  return path.resolve(__dirname, "../../..");
}

function resolveNodeBin(): string {
  if (process.env.PORTER_RESOURCES) {
    const bundled = path.join(process.env.PORTER_RESOURCES, "node");
    if (fs.existsSync(bundled)) return bundled;
  }
  try {
    return execSync("command -v node", { encoding: "utf8" }).trim();
  } catch {
    return "/usr/local/bin/node";
  }
}

function bundleVersionHint(resources: string): string {
  return readBundleVersion(resources);
}

export function isKeepAliveInstalled(): boolean {
  const plist = path.join(os.homedir(), "Library", "LaunchAgents", "local.porter.plist");
  return fs.existsSync(plist);
}

/** Write start-porter.sh contents (shared by Travel Ready + updater). */
export function writeStartPorterScript(opts?: {
  resources?: string;
  port?: number;
  version?: string;
}): string {
  const home = os.homedir();
  const support = supportDir();
  const startScript = path.join(support, "start-porter.sh");
  const root = resolvePorterRoot();
  const nodeBin = resolveNodeBin();
  const resources = opts?.resources ?? process.env.PORTER_RESOURCES ?? "";
  const port = opts?.port ?? loadConfig().port ?? 47831;
  const version = opts?.version ?? bundleVersionHint(resources);
  const cliJs = resources
    ? path.join(resources, "app/packages/core/dist/cli.js")
    : path.join(root, "packages/core/dist/cli.js");

  fs.mkdirSync(support, { recursive: true, mode: 0o755 });
  fs.mkdirSync(logsDir(), { recursive: true, mode: 0o755 });

  const startBody = `#!/bin/bash
# Auto-generated by Porter — do not edit by hand unless you know why.
set -euo pipefail
export HOME="${home}"
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:\${PATH}"
export PORTER_OPEN_BROWSER="0"
export PORTER_NO_BONJOUR="0"
export PORTER_VERSION="${version}"
${resources ? `export PORTER_RESOURCES="${resources}"` : ""}
${process.env.PORTER_UI_DIR ? `export PORTER_UI_DIR="${process.env.PORTER_UI_DIR}"` : resources ? `export PORTER_UI_DIR="${resources}/ui"` : ""}
LOG="${logsDir()}/Porter.log"
PORT="${port}"
WANT_VER="${version}"
WANT_RES="${resources}"
mkdir -p "$(dirname "$LOG")" "${support}"

health_json() {
  curl -sf -m 2 --connect-timeout 1 "http://127.0.0.1:\${PORT}/api/health" 2>/dev/null || true
}

clear_stale() {
  if lsof -nP -iTCP:"\${PORT}" -sTCP:LISTEN >/dev/null 2>&1; then
    echo "[porter-keepalive] clearing stale listener on \${PORT}" >>"$LOG"
    pkill -f 'packages/core/dist/cli.js serve' 2>/dev/null || true
    pkill -f 'Porter.app/Contents/Resources/node' 2>/dev/null || true
    sleep 0.6
  fi
}

JSON="$(health_json)"
if [[ -n "$JSON" ]]; then
  # Healthy — but take over if this bundle is newer or paths drifted (stuck old core).
  CUR_VER="$(printf '%s' "$JSON" | sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p' | head -1)"
  NEED_TAKEOVER=0
  if [[ -n "$WANT_VER" && -n "$CUR_VER" && "$WANT_VER" != "$CUR_VER" ]]; then
    # naive semver: takeover when versions differ and want looks newer (string compare + digit)
    NEED_TAKEOVER=1
  fi
  if [[ -n "$WANT_RES" ]]; then
    # If LaunchAgent points at Applications but an old translocation core is up, replace it.
    if ! lsof -nP -iTCP:"\${PORT}" -sTCP:LISTEN 2>/dev/null | grep -q "Porter.app/Contents/Resources/node\\|cli.js serve"; then
      :
    fi
  fi
  if [[ "$NEED_TAKEOVER" = "1" ]]; then
    echo "[porter-keepalive] version mismatch have=\${CUR_VER:-?} want=\${WANT_VER} — taking over" >>"$LOG"
    clear_stale
  else
    exit 0
  fi
fi

# Port held without healthy API?
if lsof -nP -iTCP:"\${PORT}" -sTCP:LISTEN >/dev/null 2>&1; then
  clear_stale
  JSON="$(health_json)"
  if [[ -n "$JSON" ]]; then
    exit 0
  fi
fi

exec "${nodeBin}" "${cliJs}" serve >>"$LOG" 2>&1
`;

  fs.writeFileSync(startScript, startBody, { mode: 0o755 });
  return startScript;
}

export function installKeepAlive(): {
  ok: boolean;
  plist: string;
  startScript: string;
  detail: string;
} {
  const home = os.homedir();
  const uid = process.getuid?.() ?? 501;
  const agents = path.join(home, "Library", "LaunchAgents");
  const plistPath = path.join(agents, "local.porter.plist");
  const resources = process.env.PORTER_RESOURCES || "";
  const port = loadConfig().port ?? 47831;
  const version = bundleVersionHint(resources);

  fs.mkdirSync(agents, { recursive: true, mode: 0o755 });
  const startScript = writeStartPorterScript({ resources, port, version });

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>local.porter</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${startScript}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>StandardOutPath</key>
  <string>${logsDir()}/Porter.launchd.out.log</string>
  <key>StandardErrorPath</key>
  <string>${logsDir()}/Porter.launchd.err.log</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>HOME</key>
    <string>${home}</string>
    <key>PATH</key>
    <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    <key>PORTER_OPEN_BROWSER</key>
    <string>0</string>
    <key>PORTER_NO_BONJOUR</key>
    <string>0</string>
    <key>PORTER_VERSION</key>
    <string>${version}</string>
${resources ? `    <key>PORTER_RESOURCES</key>\n    <string>${resources}</string>\n` : ""}  </dict>
</dict>
</plist>
`;
  fs.writeFileSync(plistPath, plist, { mode: 0o644 });

  try {
    execSync(`launchctl bootout gui/${uid}/local.porter 2>/dev/null || true`, {
      timeout: 5000,
    });
    execSync(`launchctl bootstrap gui/${uid} "${plistPath}"`, { timeout: 8000 });
  } catch (err) {
    appendActivity(
      "keepalive",
      `plist written but launchctl failed: ${err instanceof Error ? err.message : String(err)}`,
      false,
      "system",
    );
    return {
      ok: false,
      plist: plistPath,
      startScript,
      detail: "Wrote LaunchAgent but could not load it — run once from Terminal or restart Mac",
    };
  }

  const c = loadConfig();
  if (!c.awayMode) {
    c.awayMode = {
      enabled: true,
      autoStartTunnel: false,
      preventSleep: true,
      keepAliveInstalled: true,
      preferTailscaleServe: true,
      serveUrl: null,
    };
  } else {
    c.awayMode.keepAliveInstalled = true;
  }
  saveConfig(c);
  appendActivity("keepalive", `installed ${plistPath}`, true, "ui");

  return {
    ok: true,
    plist: plistPath,
    startScript,
    detail: "Porter will start at login and restart if it crashes",
  };
}

/**
 * If packaged path drifted (Downloads / App Translocation) or LaunchAgent missing while
 * away mode is on, rewrite keep-alive to the current bundle.
 */
export function maybeRepairKeepAlivePaths(): void {
  try {
    const c = loadConfig();
    if (!c.awayMode?.enabled && !c.awayMode?.keepAliveInstalled) return;
    const resources = process.env.PORTER_RESOURCES || "";
    if (!resources) return;
    if (resources.includes("AppTranslocation") || resources.includes("/Downloads/")) {
      // Don't bake broken paths — user must move to Applications
      return;
    }
    const start = path.join(supportDir(), "start-porter.sh");
    if (fs.existsSync(start)) {
      const body = fs.readFileSync(start, "utf8");
      if (body.includes(resources) && body.includes(readBundleVersion(resources))) return;
    }
    installKeepAlive();
  } catch {
    // never break serve start
  }
}

export function startPreventSleep(): void {
  if (caffeinateProc && !caffeinateProc.killed) return;
  try {
    // -i idle, -m disk, -s AC system sleep; tied to Porter PID
    caffeinateProc = spawn("caffeinate", ["-dims", "-w", String(process.pid)], {
      stdio: "ignore",
    });
    caffeinateProc.on("exit", () => {
      caffeinateProc = null;
      // Restart while away mode wants prevent-sleep
      const c = loadConfig();
      if (c.awayMode?.enabled && c.awayMode.preventSleep) {
        setTimeout(() => startPreventSleep(), 500);
      }
    });
    appendActivity("prevent_sleep", "caffeinate started", true, "system");
  } catch (err) {
    appendActivity(
      "prevent_sleep",
      err instanceof Error ? err.message : String(err),
      false,
      "system",
    );
  }
  if (!caffeinateWatch) {
    caffeinateWatch = setInterval(() => {
      const c = loadConfig();
      if (c.awayMode?.enabled && c.awayMode.preventSleep) {
        if (!caffeinateProc || caffeinateProc.killed) startPreventSleep();
      }
    }, 60_000);
    caffeinateWatch.unref?.();
  }
}

export function stopPreventSleep(): void {
  if (caffeinateWatch) {
    clearInterval(caffeinateWatch);
    caffeinateWatch = null;
  }
  if (caffeinateProc) {
    try {
      caffeinateProc.kill("SIGTERM");
    } catch {
      // ignore
    }
    caffeinateProc = null;
  }
}

export function maybeStartPreventSleep(): void {
  const c = loadConfig();
  if (c.awayMode?.enabled && c.awayMode.preventSleep) {
    startPreventSleep();
  }
}
