/**
 * Set-and-forget keep-alive for the home Mac while you travel.
 * Installs LaunchAgent + start script under Application Support (not Downloads — TCC-safe).
 */
import { execSync, spawn, type ChildProcess } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { appendActivity, loadConfig, saveConfig } from "./config.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

let caffeinateProc: ChildProcess | null = null;

export function supportDir(): string {
  return path.join(os.homedir(), "Library", "Application Support", "Porter");
}

export function logsDir(): string {
  return path.join(os.homedir(), "Library", "Logs");
}

function resolvePorterRoot(): string {
  // Prefer packaged .app resources, else monorepo root from dist/
  if (process.env.PORTER_RESOURCES) {
    return path.join(process.env.PORTER_RESOURCES, "app");
  }
  // packages/core/dist → repo root
  return path.resolve(__dirname, "../../..");
}

function resolveNodeBin(): string {
  if (process.env.PORTER_RESOURCES) {
    const bundled = path.join(process.env.PORTER_RESOURCES, "node");
    if (fs.existsSync(bundled)) return bundled;
  }
  try {
    return execSync("command -v node", { encoding: "utf8" }).trim();
  } catch {
    return "/usr/local/bin/node";
  }
}

export function isKeepAliveInstalled(): boolean {
  const plist = path.join(os.homedir(), "Library", "LaunchAgents", "local.porter.plist");
  return fs.existsSync(plist);
}

export function installKeepAlive(): {
  ok: boolean;
  plist: string;
  startScript: string;
  detail: string;
} {
  const home = os.homedir();
  const uid = process.getuid?.() ?? 501;
  const support = supportDir();
  const agents = path.join(home, "Library", "LaunchAgents");
  const plistPath = path.join(agents, "local.porter.plist");
  const startScript = path.join(support, "start-porter.sh");
  const root = resolvePorterRoot();
  const nodeBin = resolveNodeBin();
  const uiDir = process.env.PORTER_UI_DIR || path.join(root, "../ui");
  void uiDir;
  const resources = process.env.PORTER_RESOURCES || "";

  fs.mkdirSync(support, { recursive: true, mode: 0o755 });
  fs.mkdirSync(agents, { recursive: true, mode: 0o755 });
  fs.mkdirSync(logsDir(), { recursive: true, mode: 0o755 });

  const cliJs = process.env.PORTER_RESOURCES
    ? path.join(process.env.PORTER_RESOURCES, "app/packages/core/dist/cli.js")
    : path.join(root, "packages/core/dist/cli.js");

  const startBody = `#!/bin/bash
# Auto-generated by Porter — do not edit by hand unless you know why.
set -euo pipefail
export HOME="${home}"
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:\${PATH}"
export PORTER_OPEN_BROWSER="0"
export PORTER_NO_BONJOUR="0"
${resources ? `export PORTER_RESOURCES="${resources}"` : ""}
${process.env.PORTER_UI_DIR ? `export PORTER_UI_DIR="${process.env.PORTER_UI_DIR}"` : resources ? `export PORTER_UI_DIR="${resources}/ui"` : ""}
LOG="${logsDir()}/Porter.log"
mkdir -p "$(dirname "$LOG")" "${support}"

if curl -sf -m 1 --connect-timeout 1 "http://127.0.0.1:47831/api/health" >/dev/null 2>&1; then
  exit 0
fi

exec "${nodeBin}" "${cliJs}" serve >>"$LOG" 2>&1
`;

  fs.writeFileSync(startScript, startBody, { mode: 0o755 });

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>local.porter</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${startScript}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>StandardOutPath</key>
  <string>${logsDir()}/Porter.launchd.out.log</string>
  <key>StandardErrorPath</key>
  <string>${logsDir()}/Porter.launchd.err.log</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>HOME</key>
    <string>${home}</string>
    <key>PATH</key>
    <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    <key>PORTER_OPEN_BROWSER</key>
    <string>0</string>
    <key>PORTER_NO_BONJOUR</key>
    <string>0</string>
  </dict>
</dict>
</plist>
`;
  fs.writeFileSync(plistPath, plist, { mode: 0o644 });

  try {
    execSync(`launchctl bootout gui/${uid}/local.porter 2>/dev/null || true`, {
      timeout: 5000,
    });
    execSync(`launchctl bootstrap gui/${uid} "${plistPath}"`, { timeout: 8000 });
  } catch (err) {
    appendActivity(
      "keepalive",
      `plist written but launchctl failed: ${err instanceof Error ? err.message : String(err)}`,
      false,
      "system",
    );
    return {
      ok: false,
      plist: plistPath,
      startScript,
      detail: "Wrote LaunchAgent but could not load it — run once from Terminal or restart Mac",
    };
  }

  const c = loadConfig();
  if (!c.awayMode) {
    c.awayMode = {
      enabled: true,
      autoStartTunnel: true,
      preventSleep: true,
      keepAliveInstalled: true,
    };
  } else {
    c.awayMode.keepAliveInstalled = true;
  }
  saveConfig(c);
  appendActivity("keepalive", `installed ${plistPath}`, true, "ui");

  return {
    ok: true,
    plist: plistPath,
    startScript,
    detail: "Porter will start at login and restart if it crashes",
  };
}

export function startPreventSleep(): void {
  if (caffeinateProc && !caffeinateProc.killed) return;
  try {
    // -i idle, -m disk, -s AC system sleep; tied to Porter PID
    caffeinateProc = spawn("caffeinate", ["-dims", "-w", String(process.pid)], {
      stdio: "ignore",
    });
    caffeinateProc.on("exit", () => {
      caffeinateProc = null;
    });
    appendActivity("prevent_sleep", "caffeinate started", true, "system");
  } catch (err) {
    appendActivity(
      "prevent_sleep",
      err instanceof Error ? err.message : String(err),
      false,
      "system",
    );
  }
}

export function stopPreventSleep(): void {
  if (caffeinateProc) {
    try {
      caffeinateProc.kill("SIGTERM");
    } catch {
      // ignore
    }
    caffeinateProc = null;
  }
}

export function maybeStartPreventSleep(): void {
  const c = loadConfig();
  if (c.awayMode?.enabled && c.awayMode.preventSleep) {
    startPreventSleep();
  }
}
